"""add sedistance field to parcel model

Revision ID: 23f3817fd2ff
Revises: 7c91d55e23ee
Create Date: 2026-09-16 14:23:12.078530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f3817fd2ff'
down_revision = '7c91d55e23ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
