"""add street_address to locations

Revision ID: 428542e9b622
Revises: da50bae00003
Create Date: 2026-09-16 17:06:26.289572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428542e9b622'
down_revision = 'da50bae00003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('street_address')

    # ### end Alembic commands ###
