"""add title and data to notifications

Revision ID: 5a45ef1f2af1
Revises: b02110544d0f
Create Date: 2026-09-02 13:44:26.755984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a45ef1f2af1'
down_revision = 'b02110544d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.alter_column('parcel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('parcel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('data')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
