"""add sender/receiver details and package description to parcel model

Revision ID: 7c91d55e23ee
Revises: 5a45ef1f2af1
Create Date: 2026-09-16 11:55:41.808785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c91d55e23ee'
down_revision = '5a45ef1f2af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('parcel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_fragile', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sender_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sender_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receiver_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('receiver_phone', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_phone')
        batch_op.drop_column('receiver_email')
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('sender_phone')
        batch_op.drop_column('sender_email')
        batch_op.drop_column('sender_name')
        batch_op.drop_column('notes')
        batch_op.drop_column('is_fragile')
        batch_op.drop_column('description')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('parcel_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
