"""add location fields to users

Revision ID: b02110544d0f
Revises: db823df70499
Create Date: 2026-09-02 11:46:14.034507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02110544d0f'
down_revision = 'db823df70499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_location_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_location_update')
        batch_op.drop_column('current_longitude')
        batch_op.drop_column('current_latitude')

    # ### end Alembic commands ###
