"""add composite index on parcels(user_id, created_at)

Revision ID: da50bae00003
Revises: 23f3817fd2ff
Create Date: 2026-09-16 15:02:40.084397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da50bae00003'
down_revision = '23f3817fd2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.create_index('ix_parcels_user_created', ['user_id', sa.literal_column('created_at DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index('ix_parcels_user_created')

    # ### end Alembic commands ###
