"""Add rider fields and fix relationships

Revision ID: db823df70499
Revises: dab25c4c8a7c
Create Date: 2026-09-02 00:35:14.824736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db823df70499'
down_revision = 'dab25c4c8a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rider_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['rider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rider_id')

    # ### end Alembic commands ###
